{"@class": "de.fau.cs.inf2.cthree.data.Cluster", "id": "a97c8c74c84bf8ab0df90733f271564e", "detectedBy": ["DIFF_HIERARCHICAL", "DIFF_DBSCAN"], "members": [{"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "ad6b7ed2108a9cd13012ced0951598be", "repository": "https://github.com/cobertura/cobertura.git", "fileName": "cobertura/test/net/sourceforge/cobertura/reporting/xml/JUnitXMLParserEntityResolver.java", "commitBeforeChange": "b5fae504c12a9486e23c38b8e2fb563abfcdacb8", "commitAfterChange": "07248c03e606fdd0a9127de1412cff71c208bc4a", "methodNumberBeforeChange": 1, "methodNumberAfterChange": 1, "signatureBeforeChange": "  \tpublic InputSource resolveEntity(String publicId, String systemId) \t\t\tthrows SAXException", "signatureAfterChange": "  \tpublic InputSource resolveEntity(String publicId, String systemId) \t\t\tthrows SAXException", "diff": ["-\t\t\tif (systemId.endsWith(coverageDTD))", "+\t\t\tif (systemId.endsWith(XMLReport.coverageDTD))", "-\t\t    // apparently 1.5 throws an IOException here, but we can't catch it specifically if", "-\t\t    //\twe're not on 1.5 (docs on both kind of say that they throw it)", "-\t\t    //\tactual code on 1.4.2 has it remmed out so that it only throws SAXException  ", "+\t\t\t// apparently 1.5 throws an IOException here, but we can't catch it specifically if", "+\t\t\t//\twe're not on 1.5 (docs on both kind of say that they throw it)", "+\t\t\t//\tactual code on 1.4.2 has it remmed out so that it only throws SAXException  "]}, {"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "f2d0460eac0ebf431005b83c8434da3f", "repository": "https://github.com/cobertura/cobertura.git", "fileName": "cobertura/test/net/sourceforge/cobertura/reporting/xml/JUnitXMLParserEntityResolver.java", "commitBeforeChange": "80dc02a26a18bbc7987412c491ef81bbcc411419", "commitAfterChange": "aa28e2370adfa8f4e4ecc6102e67283dbce474d8", "methodNumberBeforeChange": 1, "methodNumberAfterChange": 1, "signatureBeforeChange": "  \tpublic InputSource resolveEntity(String publicId, String systemId) \t\t\tthrows SAXException", "signatureAfterChange": "  \tpublic InputSource resolveEntity(String publicId, String systemId) \t\t\tthrows SAXException", "diff": ["-\t\treturn super.resolveEntity(publicId, systemId);", "+\t\tInputSource source = null;", "+", "+\t\ttry {", "+\t\t\tsuper.resolveEntity(publicId, systemId);", "+\t\t} catch (Exception exception) {", "+\t\t    // apparently 1.5 throws an IOException here, but we can't catch it specifically if", "+\t\t    //\twe're not on 1.5 (docs on both kind of say that they throw it)", "+\t\t    //\tactual code on 1.4.2 has it remmed out so that it only throws SAXException  ", "+\t\t\tthrow new SAXException(exception);", "+\t\t}", "+", "+\t\treturn source;"]}]}