{"@class": "de.fau.cs.inf2.cthree.data.Cluster", "id": "988547e975ce1831e6f55e0aa2ea6c83", "detectedBy": ["DIFF_DBSCAN"], "members": [{"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "b7ee7edc8fae8982196a8947513bc95b", "repository": "http://git.code.sf.net/p/drjava/git_repo", "fileName": "drjava/src/edu/rice/cs/drjava/model/debug/jpda/JPDADebugger.java", "commitBeforeChange": "27f4730bb628f4f21b5ace9b8592e93a615017f8", "commitAfterChange": "08f616afaebe02cc02ba5da4da4990852caead81", "methodNumberBeforeChange": 23, "methodNumberAfterChange": 21, "signatureBeforeChange": "   public synchronized void removeWatch(String field) throws DebugException", "signatureAfterChange": "   public void removeWatch(String field) throws DebugException", "diff": ["-  public synchronized void removeWatch(String field) throws DebugException {", "+  public /* synchronized */ void removeWatch(String field) throws DebugException {", "-    ", "+    assert EventQueue.isDispatchThread();", "-        Utilities.invokeLater(new Runnable() { public void run() { _notifier.watchRemoved(watch); } });", "+//        Utilities.invokeLater(new Runnable() { public void run() { ", "+          _notifier.watchRemoved(watch); ", "+//        } });"]}, {"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "f1747a665a374c7511d096dc8c6ed1d9", "repository": "http://git.code.sf.net/p/drjava/git_repo", "fileName": "drjava/src/edu/rice/cs/drjava/model/debug/JPDADebugger.java", "commitBeforeChange": "1555d1cb14e076ea1030f08b3fde8f9710fe3a1d", "commitAfterChange": "c0d7f23f7940c03c6774a2c608b9ab495655e5b1", "methodNumberBeforeChange": 11, "methodNumberAfterChange": 11, "signatureBeforeChange": "   public synchronized void startup() throws DebugException", "signatureAfterChange": "   public synchronized void startUp() throws DebugException", "diff": ["-  public synchronized void startup() throws DebugException {", "+  public synchronized void startUp() throws DebugException {", "-      _attachToVM();", "+      try { _attachToVM(); }", "+      catch(DebugException e1) {  // We sometimes see ConnectExceptions stating that the connection was refused", "+        try { _attachToVM(); }", "+        catch(DebugException e2) { _attachToVM(); }  // if we throw another exception, three strikes and we're out", "+      }"]}], "num": 19222}