{"@class": "de.fau.cs.inf2.cthree.data.Cluster", "id": "3a30fbadcbd284444b40ad3caba2689f", "detectedBy": ["DIFF_DBSCAN"], "members": [{"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "245600b2c762756f6fbd766e82158d02", "repository": "https://git-wip-us.apache.org/repos/asf/ant.git", "fileName": "src/tests/junit/org/apache/tools/ant/taskdefs/optional/script/ScriptDefTest.java", "commitBeforeChange": "7eab7687db21f8a0c35b66dd9fae9e7c1178d5d5", "commitAfterChange": "b61c80746dd5df73899390826e197d2656784f91", "methodNumberBeforeChange": 7, "methodNumberAfterChange": 6, "signatureBeforeChange": "      public void testException()", "signatureAfterChange": "      @Test     public void testException()", "diff": ["+    @Test", "-        expectBuildExceptionContaining(\"exception\",", "-            \"Should have thrown an exception in the script\",", "-            \"TypeError\");", "+        try {", "+            buildRule.executeTarget(\"exception\");", "+            fail(\"Should have thrown an exception in the script\");", "+        } catch(BuildException ex) {", "+            AntAssert.assertContains(\"TypeError\", ex.getMessage());", "+        }"]}, {"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "927dead89c94cc642639155ff4d09176", "repository": "https://git-wip-us.apache.org/repos/asf/ant.git", "fileName": "src/tests/junit/org/apache/tools/ant/taskdefs/condition/IsReachableTest.java", "commitBeforeChange": "7eab7687db21f8a0c35b66dd9fae9e7c1178d5d5", "commitAfterChange": "b61c80746dd5df73899390826e197d2656784f91", "methodNumberBeforeChange": 10, "methodNumberAfterChange": 9, "signatureBeforeChange": "      public void testBadURL() throws Exception", "signatureAfterChange": "      @Test     public void testBadURL() throws Exception", "diff": ["+    @Test", "-        expectBuildExceptionContaining(\"testBadURL\",", "-                \"error in URL\",", "-                IsReachable.ERROR_BAD_URL);", "+        try {", "+            buildRule.executeTarget(\"testBadURL\");", "+            fail(\"Build exception expected: error in URL\");", "+        } catch(BuildException ex) {", "+            AntAssert.assertContains(IsReachable.ERROR_BAD_URL, ex.getMessage());", "+        }"]}]}