{"@class": "de.fau.cs.inf2.cthree.data.Cluster", "id": "a259c58f08f9a9c92233e4494f70792e", "detectedBy": ["DIFF_DBSCAN"], "members": [{"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "2e772322c117a1e7f9494be4beb5a744", "repository": "http://git.code.sf.net/p/drjava/git_repo", "fileName": "drjava/src/edu/rice/cs/drjava/model/junit/DefaultJUnitModel.java", "commitBeforeChange": "d1a5d27cb22a5cf8891a6811cdc476b60834d1c0", "commitAfterChange": "eb9337b4d6e2d2de4c1774413f08dfb947ae389c", "methodNumberBeforeChange": 10, "methodNumberAfterChange": 10, "signatureBeforeChange": "      private void junitOpenDefDocs(List<OpenDefinitionsDocument> lod, boolean allTests)", "signatureAfterChange": "      private void junitOpenDefDocs(List<OpenDefinitionsDocument> lod, boolean allTests)", "diff": ["-      catch(IOException e) { ", "+      catch(IOException e) {", "+        // Probably a java.rmi.UnmarshalException caused by the interruption of unit testing.", "+        // Swallow the exception and proceed.", "-        throw new UnexpectedException(e); ", "+        synchronized (this) { _testInProgress = false;}", "+        throw new UnexpectedException(e);"]}, {"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "67aa4976815e5b96cad64b0fea22c9f4", "repository": "http://git.code.sf.net/p/drjava/git_repo", "fileName": "drjava/src/edu/rice/cs/drjava/ui/CompilerErrorPanel.java", "commitBeforeChange": "7b4a527a2fd4010c88a2ef6ea8f158547b322968", "commitAfterChange": "7b22fbe0160e9fdc451caeb623e46b870b03ccd3", "methodNumberBeforeChange": 17, "methodNumberAfterChange": 17, "signatureBeforeChange": "   private void _createPositionsArray()", "signatureAfterChange": "   private void _createPositionsArray()", "diff": ["+    DrJava.consoleErr().println(\"created pos arr: \" + _errorPositions.length);", "+      DrJava.consoleErr().println(\"got defs text, len=\" + defsText.length());", "+        DrJava.consoleErr().println(\"num processed: \" + numProcessed);", "+", "-    catch (BadLocationException willNeverEverEverHappen) {", "+    catch (BadLocationException ble) {", "+      throw new UnexpectedException(ble);"]}], "num": 14415}