{"@class": "de.fau.cs.inf2.cthree.data.Cluster", "id": "a929a2f2754f6e8d96d1703f29e1636f", "detectedBy": ["DIFF_HIERARCHICAL", "DIFF_DBSCAN"], "members": [{"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "05c48839952035fd18a28398373e36ca", "repository": "https://github.com/junit-team/junit.git", "fileName": "src/main/java/org/junit/Assert.java", "commitBeforeChange": "6e6a6e47f15e3de1fac90ecb9e3dbdb180f3a88b", "commitAfterChange": "f1be7f250156ecc0e6b6c9d7005abb53359fe2fe", "methodNumberBeforeChange": 61, "methodNumberAfterChange": 61, "signatureBeforeChange": " \tpublic static <T> void assertThat(String reason, T actual, \t\t\tMatcher<? super T> matcher)", "signatureAfterChange": " \tpublic static <T> void assertThat(String reason, T actual, \t\t\tMatcher<? super T> matcher)", "diff": ["-\t\ttry {", "-\t\t\tMatcherAssert.assertThat(reason, actual, matcher);", "-\t\t} catch (AssertionError assertionError) {", "-\t\t\tif (actual instanceof Throwable)", "-\t\t\t\tassertionError.initCause((Throwable) actual);", "-\t\t\tthrow assertionError;", "-\t\t}", "+\t\tMatcherAssert.assertThat(reason, actual, matcher);"]}, {"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "62edc2087eee27c37813f4e33e9aaab7", "repository": "https://github.com/junit-team/junit.git", "fileName": "src/main/java/org/junit/Assert.java", "commitBeforeChange": "126b8eb8d9e550bfe3bbb03ff92b047172d928bb", "commitAfterChange": "53929101b4d9606d92dfd8d52e87f5dda467d51a", "methodNumberBeforeChange": 49, "methodNumberAfterChange": 49, "signatureBeforeChange": " \tpublic static <T> void assertThat(String reason, T actual, \t\t\tMatcher<? super T> matcher)", "signatureAfterChange": " \tpublic static <T> void assertThat(String reason, T actual, \t\t\tMatcher<? super T> matcher)", "diff": ["-\t\t\tthrow new java.lang.AssertionError(description.toString());", "-\t\t}", "+\t\t\tjava.lang.AssertionError assertionError= new java.lang.AssertionError(", "+\t\t\t\t\tdescription.toString());", "+\t\t\tif (actual instanceof Throwable)", "+\t\t\t\tassertionError.initCause((Throwable) actual);", "+\t\t\tthrow assertionError;", "+\t}"]}]}