{"@class": "de.fau.cs.inf2.cthree.data.Cluster", "id": "64c766c7f42f7beeb48c15f8d06c79b5", "detectedBy": ["DIFF_HIERARCHICAL"], "members": [{"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "7382271bb53c86cb74e5e858d568463a", "repository": "https://github.com/junit-team/junit.git", "fileName": "src/org/junit/internal/runners/JUnit4MethodRunner.java", "commitBeforeChange": "a58514aec7e843339be24980e92aeeb759327ffb", "commitAfterChange": "57302f0df76fba83ba72a676bd660efeb5881af6", "methodNumberBeforeChange": 19, "methodNumberAfterChange": 19, "signatureBeforeChange": " \t \tprotected void run(Roadie context)", "signatureAfterChange": " \t \tprotected void run(Roadie context)", "diff": ["-\t\tchain().run(context);", "+\t\ttry {", "+\t\t\tchain().run(context);", "+\t\t} catch (StoppedByUserException e) {", "+\t\t\tthrow e;", "+\t\t} catch (Throwable e) {", "+\t\t\tthrow new RuntimeException(\"Unexpected error running tests\", e);", "+\t\t}"]}, {"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "c074550617df1058e52ddff528a7eee6", "repository": "https://github.com/junit-team/junit.git", "fileName": "junit/framework/TestCase.java", "commitBeforeChange": "3b5085dec3f1fd578c5109114bd02370bea48fda", "commitAfterChange": "ffd5f087e9b0ffaf146c91323adcf0ffdf469b0f", "methodNumberBeforeChange": 6, "methodNumberAfterChange": 6, "signatureBeforeChange": " \tpublic void runBare() throws Throwable", "signatureAfterChange": " \tpublic void runBare() throws Throwable", "diff": ["+\t\tThrowable running= null;", "+\t\t} catch (Throwable e) {", "+\t\t\trunning= e;", "-\t\t\ttearDown();", "+\t\t\ttry {", "+\t\t\t\ttearDown();", "+\t\t\t} catch (Exception e) {", "+\t\t\t\tthrow (running != null) ? running : e;", "+\t\t\t}"]}]}